# Generated by Django 5.1.1 on 2024-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol_code", models.CharField(max_length=15)),
                ("sector_code", models.CharField(max_length=5)),
                ("company_short_name", models.CharField(max_length=25)),
                ("opening_rate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("highest_rate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("lowest_rate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("current_rate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("current_turnover", models.IntegerField()),
                (
                    "lastday_closing_price",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
            ],
        ),
    ]
